In [5]:
#----------------------------
# import libraries
#----------------------------
import numpy as np
import pandas as pd
#import scipy.io as sio
from matplotlib import pyplot as plt
#----------------------------
# scikit-learn
#----------------------------
# preprocessing
#from sklearn.preprocessing import StandardScaler
#from sklearn.preprocessing import OneHotEncoder
# neural network
#from sklearn.neural_network import MLPClassifier
# metrics
#from sklearn.metrics import confusion_matrix
#from sklearn.metrics import f1_score
#from sklearn.metrics import accuracy_score
#from sklearn.metrics import zero_one_loss
#from sklearn.metrics import log_loss
#from sklearn.metrics import roc_curve
#from sklearn.metrics import roc_auc_score

In [6]:
#use numpy fixed point notation
np.set_printoptions(suppress=True)
#----------------------------
# disable convergence warning
#from sklearn.utils.testing import ignore_warnings
#from sklearn.exceptions import ConvergenceWarning
#----------------------------
# path to save figures
path = '../figures/k-means/'

# Reading the dataset (.mat file)

In [7]:
from os.path import abspath, join
# get the root dir ('current_dir/..')
root_dir = abspath('..')
dataset_dir = join(root_dir, 'dataset')

In [10]:
import zipfile
# set dataset files path
file_path = join(dataset_dir, 'microdados_enem2018.zip')
# read zip files
zf = zipfile.ZipFile(file_path)
df = pd.read_csv(zf.open('DADOS/MICRODADOS_ENEM_2018.csv'), sep=';', encoding='cp1252')

In [12]:
df

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025,Q026,Q027
0,180008202043,2018,5300108,Brasília,53,DF,44.0,M,1.0,1,...,A,A,A,A,A,A,A,A,B,A
1,180007197856,2018,2111102,São João dos Patos,21,MA,23.0,F,0.0,3,...,A,B,A,A,B,A,A,A,A,A
2,180008517434,2018,3530607,Mogi das Cruzes,35,SP,23.0,F,0.0,1,...,A,B,A,A,B,B,B,B,A,A
3,180007661228,2018,2916401,Itapetinga,29,BA,26.0,F,0.0,3,...,A,B,B,A,C,A,B,B,A,A
4,180008787987,2018,2918100,Jeremoabo,29,BA,20.0,M,0.0,0,...,A,B,A,A,B,A,B,B,B,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5513742,180013945649,2018,3304557,Rio de Janeiro,33,RJ,56.0,F,1.0,1,...,B,B,A,A,B,B,A,A,A,C
5513743,180013964149,2018,1302603,Manaus,13,AM,20.0,F,0.0,3,...,A,A,A,A,B,A,A,B,B,A
5513744,180013980226,2018,3550308,São Paulo,35,SP,17.0,F,0.0,3,...,A,A,A,B,B,A,B,B,B,A
5513745,180013934137,2018,3509502,Campinas,35,SP,17.0,F,0.0,1,...,B,C,B,B,E,A,C,B,B,C
5513746,180013962906,2018,3127701,Governador Valadares,31,MG,21.0,M,0.0,3,...,A,A,A,A,B,A,A,B,A,A

In [14]:
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

In [17]:
kmeans = KMeans(
    n_clusters = 8, 
    init = 'k-means++', 
    n_init = 10, 
    max_iter = 300, 
    tol = 0.0001, 
    precompute_distances = 'auto', 
    verbose = 0, 
    random_state = None, 
    copy_x = True, 
    n_jobs = None, 
    algorithm = 'auto',
)